apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  {{- if not (or .Values.hpa .Values.hpav2 ((.Values.KEDA).ScaledObject)) }}
  replicas: {{ .Values.replicaCount }}
  {{- end}}
  strategy:
  {{- if hasKey .Values.deployment "strategy" }}
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  {{- else}}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  {{- end}}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      {{- if hasKey .Values.deployment "annotations" }}
      annotations:
        {{- range $key, $value := .Values.deployment.annotations }}
        {{ $key | quote }} : {{ $value | quote }}
        {{- end }}
      {{- end}}
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if hasKey .Values "tolerations" }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end}}
      {{- if hasKey .Values "nodeSelector" }}
      nodeSelector:
        {{ .Values.nodeSelector.labelName }}: {{ .Values.nodeSelector.labelValue }} 
      {{- end}}
      {{- if hasKey .Values "affinity" }}
      affinity:
        {{- if hasKey .Values.affinity "nodeAffinity" }}
        nodeAffinity: {{- toYaml .Values.affinity.nodeAffinity | nindent 10 }}
        {{- end }}
        {{- if hasKey .Values.affinity "podAffinity" }}
        podAffinity: {{- toYaml .Values.affinity.podAffinity | nindent 10 }}
        {{- end }}
        podAntiAffinity:
          {{- if hasKey .Values.affinity.podAntiAffinity "requiredDuringSchedulingIgnoredDuringExecution" }}
          requiredDuringSchedulingIgnoredDuringExecution: {{- toYaml .Values.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 12 }}
          {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- if hasKey .Values.affinity.podAntiAffinity "preferredDuringSchedulingIgnoredDuringExecution" }}
            {{- toYaml .Values.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution | nindent 12 }}
          {{- end }}
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Values.name }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Values.name }}
                topologyKey: kubernetes.io/hostname
              weight: 99
      {{- end }}
      {{- if hasKey .Values "securityContextForPod" }}
      securityContext: 
        {{ toYaml .Values.securityContextForPod | nindent 8 }}        
      {{- end}}
      containers:
{{- if hasKey .Values.deployment "containers" }}
  {{- range .Values.deployment.containers }}
      - {{ template "deployment.container" . }}
  {{- end}}
{{- else}}
      - {{ template "deployment.container_legacy" .Values }}
{{- end}}
      {{- if hasKey .Values.deployment  "volumes" }}
      volumes:
        {{- range $key, $vol := $.Values.deployment.volumes }}
        - name: {{ $vol.name }}
          {{- if hasKey $vol "secret" }}
          secret:
            {{- toYaml $vol.secret | nindent 12 }}
          {{- end }}
          {{- if hasKey $vol "configMap" }}
          configMap:
            name: {{ $vol.name }}
          {{- end }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.serviceaccount}}
      serviceAccountName: {{ .Values.serviceaccount.name | default (printf "%s-pod-service-account" .Values.name) }}
      {{- end }}
      {{- if .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.deployment.dnsConfig | nindent 8 }}
      {{- else }}
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds | default "61" }}
